### ISSUE TITLE
Maximized and browser back button

### ISSUE THREAD

**Issue by kzimny** [ckeditor/ckeditor4-angular#141] opened 2020-09-30 07:01 UTC
When user click on full-screen button from toolbars and press back button of browser then ui getting broken.
Stackblitz editor: https://stackblitz.com/edit/angular-ivy-wxq5w9
Stackblitz demo: https://angular-ivy-wxq5w9.stackblitz.io/

![20200930_085502](https://user-images.githubusercontent.com/12007674/94653025-3427c300-02fb-11eb-9678-1075d28ef0e0.gif)

**Comment by Dumluregn** [comment] 2020-09-30 07:26
Hello!
I couldn't reproduce the issue in SB editor, but unfortunately I did in demo and in our sample. Thank you for the report.

**Comment by kzimny** [comment] 2020-09-30 17:22
Dear Darek, thank you for your quick response. It seems that the [maximize plugin](https://github.com/ckeditor/ckeditor4/blob/master/plugins/maximize/plugin.js) works in "MAXIMIZE way" only and there is no option to call MINIMIZE programatically. I tried to use `beforeDestroy` event with no luck:
``` 
      this.instance.on('beforeDestroy', (evt: any) => {
        if (this.instance.getCommand('maximize').state === 1) {
          const command = this.instance.getCommand('maximize');
          command.setState(CKEDITOR.TRISTATE_OFF);
          // CKEDITOR.fire('maximize', CKEDITOR.TRISTATE_OFF);
        }
      });
```

**Comment by kzimny** [comment] 2020-11-04 08:08
Any news on this issue?

**Comment by Dumluregn** [comment] 2020-12-08 14:04
Hi @kzimny, sorry for the late response. As the issue concerns all single page applications (not just those created with Angular), we decided that this should be implemented in the `maximize` plugin itself - see https://github.com/ckeditor/ckeditor4/issues/4374. We are currently working on it, so there are chances this fix will be included in the next CKEditor 4 release (release date is not set yet though).

By the way please notice, that to minimize the editor you simply need to call `maximize` command again once it is active rather than trying to disable it.

**Comment by kzimny** [comment] 2020-12-08 15:02
Great news! Thank you for the information.

**Comment by jacekbogdanski** [comment] 2021-08-18 07:27
Closing as CKEditor 4 upstream.

**Closed by jacekbogdanski** 2021-08-18 07:27 UTC
Labels: status:confirmed, type:bug, size:S

**Comment by kzimny** [comment] 2021-08-18 14:10
The issue still exist in ckeditor4-angular v.2.2.2, ckeditor v.4.16.2. Please explain why the task is closed.

**Comment by jacekbogdanski** [comment] 2021-08-18 14:17
@kzimny the issue is not directly related to how Angular integration works but CKEditor 4. We will be fixing it in CKEditor 4 directly.

You can follow this ticket https://github.com/ckeditor/ckeditor4/issues/4374 for more updates on the issue status. Once it's fixed, the changes will be released for the next CKEditor 4 minor/major release (depending on which one comes first).

**Comment by kzimny** [comment] 2021-11-29 08:34
@jacekbogdanski thank you. It works in v.4.17.1
