### ISSUE TITLE
tabIndex not working

### ISSUE THREAD

**Issue by jindalrohit** [ckeditor/ckeditor4-angular#41] opened 2019-07-18 09:48 UTC
@f1ames : I am using the code below but tab index is not working.

```
<ckeditor [config]="{tabIndex:2, toolbar: [ 'bold', 'italic' ]}" [editor]="Editor" name="item"
                [(ngModel)]="item"></ckeditor>
````

**Comment by f1ames** [comment] 2019-08-19 12:44
Could you add more details on this issue, what is your expected behaviour (do you have other elements with `tabindex` attribute, etc) and what is actual behaviour?

The `tabIndex` config works fine in CKEditor 4 itself (see https://s.codepen.io/f1ames/debug/mdbreYq/yoAZEOzjDYjr) so it should also work fine for Angular integration 🤔

**Comment by Dumluregn** [comment] 2019-10-28 12:32
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free to provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2019-10-28 12:32 UTC
Labels: question
