### ISSUE TITLE
508 Accessibility - issue on ckeditor

### ISSUE THREAD

**Issue by RahulPatil-REISys** [ckeditor/ckeditor4-angular#241] opened 2023-04-14 07:30 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Integrated ckeditor. Found following issues by using various accessibility tools like Sortsite and Wave.

**Sortsite tool**

**Warning** - 
    1. aria-disabled=true should not be used on links. If a link needs to be disabled, remove the href attribute. 

**Wave tool**

**Error**  -   Missing form label
**Warning**  - Very small text

Please Guide for clearing such errors and warnings.

**Comment by Comandeer** [comment] 2023-04-14 09:41
Could you provide more information about where these issues are present?

**Comment by RahulPatil-REISys** [comment] 2023-04-17 09:35
Please refer to the screenshot attached.

Wave tool Error - Missing form label

![missing-form-label](https://user-images.githubusercontent.com/4630746/232439224-d6df0253-8323-4aa6-a2be-2f236c90fc42.png)

Wave Tool Warning - Very small text
![very-small-text](https://user-images.githubusercontent.com/4630746/232441876-d3fa9b9c-91b8-441e-8cf1-09fa09f0aeaa.png)

Sortsite Tool Warning - aria-disabled=true should not be used on links. If a link needs to be disabled, remove the href attribute.
![sortsite](https://user-images.githubusercontent.com/4630746/232445405-22f015f2-2696-440d-9ad1-9850471851c0.PNG)

**Comment by Comandeer** [comment] 2023-04-17 11:05
> **Error** - Missing form label

If I understand the screen correctly, this error points to the hidden `textarea` that is replaced by the editor's instance. In that case, properly labeling the element is a task of the integrator and it's not part of the editor.

> **Warning** -  
> 1\. aria-disabled=true should not be used on links. If a link needs to be disabled, remove the href attribute.

Per [ARIA specification](https://w3c.github.io/aria/#aria-disabled):

> While [`aria-disabled`](https://w3c.github.io/aria/#aria-disabled) and proper scripting can successfully disable an element with role [`link`](https://w3c.github.io/aria/#link), fully disabling a host language equivalent can be problematic. Authors are advised not to use [`aria-disabled`](https://w3c.github.io/aria/#aria-disabled) on elements that cannot be disabled through features of the host language alone.

This warning is not applicable in the context of the editor as the intended behavior is only to disable the click action and keep the element focusable. The specification points to it as the acceptable behavior:

> Disabled elements might not receive focus from the tab order.

> **Warning** - Very small text

This seems to be an error on the WAVE side as it's present only when the styles for the page are switched off. According to the tool, it's for the text that has a 10px or lower font size – but the marked-up text has a 16px font size. The error is not present at all if styles aren't switched off.

As none of the reported issues are applicable to the editor, I'm closing the issue.

**Closed by Comandeer** 2023-04-17 11:05 UTC
