### ISSUE TITLE
No Source button found for inline type ckeditor

### ISSUE THREAD

**Issue by manjurhusen** [ckeditor/ckeditor4-angular#135] opened 2020-09-12 05:40 UTC
Here is the demo https://ckeditor.com/docs/ckeditor4/latest/examples/angular.html#/editor-types

When I select "Choose editor type: Inline Editor" it is not showing Source button.

Based on this document - https://ckeditor.com/docs/ckeditor4/latest/examples/sourcearea.html, I have downloaded and added "SourceDialog" plugin from here https://ckeditor.com/cke4/addon/sourcedialog and added but it is not working.

**Comment by Dumluregn** [comment] 2020-09-15 08:49
Hello,

in the documentation the `sourcedialog` plugin is not included, so it is an expected behaviour that Source button is not shown. Could you provide another example presenting this issue, e.g. using [Stackblitz](https://stackblitz.com/edit/angular-ivy-gm4fbb)?

**Comment by jacekbogdanski** [comment] 2020-09-29 07:15
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-09-29 07:15 UTC
Labels: resolution:expired

**Comment by manjurhusen** [comment] 2020-09-29 11:11
I have tried but still not showing. Can you please update demo with source button in "Inline CkEditor" here https://ckeditor.com/docs/ckeditor4/latest/examples/angular.html#/editor-types

This will help all the developers.

**Comment by Dumluregn** [comment] 2020-09-29 12:26
It seems to be a reasonable request. I've created an [issue](https://github.com/ckeditor/ckeditor4/issues/4305) to cover this change. Thanks for the suggestion!

**Comment by manjurhusen** [comment] 2020-09-29 12:51
@Dumluregn  Thank you for request.
